Task/221 implement insert adjacent functions
capricorn86/happy-dom pull request #228
Opened 2021-03-12 14:18 UTC by dkocsis-emarsys

Hi!

I've finished with the changes related to the insertAdjacent functionalities and the missing implementation if insertBefore's null parameter handling.
If there's anything i should change, just tell me.
As for the solution, i basically went with a polyfill like solution, because it looked just fine to add this new functionality without write huge chunks of code. That's why i had to fix insertBefore, it depends on that missing behaviour.

2021-03-12 22:35 UTC, capricorn86 requested changes
Looks really good and thank you for contributing! :+1: 

I just have some minor comments :slightly_smiling_face:

2021-03-12 22:35 UTC, capricorn86 commented on packages/happy-dom/src/nodes/node/INode.ts
> +	insertAdjacentElement(position: TInsertAdjacentPositions, node: INode): INode | null;
insertAdjacentElement(), insertAdjacentHTML(), insertAdjacentText() is part of the IElement interface and should be implemented in the Element class.

2021-03-12 22:35 UTC, capricorn86 commented on packages/happy-dom/src/nodes/node/Node.ts
> +	public insertAdjacentElement(position: TInsertAdjacentPositions, element: INode): INode | null {
insertAdjacentElement(), insertAdjacentHTML(), insertAdjacentText() is part of the IElement interface and should be implemented in the Element class.

2021-03-12 22:35 UTC, capricorn86 commented on packages/happy-dom/src/nodes/node/Node.ts
> +		this.insertAdjacentElement(position, templateElement.content);
```suggestion
		for(const node of XMLParser.parse(text).childNodes.slice()) {
		      this.insertAdjacentElement(position, node);
		}
```
I think we can use the XMLParser directly here :slightly_smiling_face: 

Note that you need to prepend the commit with "#228@minor:" if you apply the suggestion as well.

2021-03-12 22:36 UTC, capricorn86 commented
The tests where really good by the way :+1:

2021-03-16 11:11 UTC, dkocsis-emarsys commented
Thanks for the review, I've made the requested changes.
I've used #221 for moving the things to the Element class and #228 for the suggestion.

2021-03-16 22:32 UTC, capricorn86 approved these changes
Awesome work! :+1:

2021-03-16 22:32 UTC, merged