#681@patch: Add scrollX, scrollY, pageXOffset, pageYOffset to window.
capricorn86/happy-dom pull request #681
Opened 2022-12-19 07:32 UTC by Ben2HellAndBack

Add [scrollX](https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollX), [scrollY](https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollY), [pageXOffset](https://developer.mozilla.org/en-US/docs/Web/API/Window/pageXOffset) and [pageYOffset](https://developer.mozilla.org/en-US/docs/Web/API/Window/pageYOffset)  to `Window`

2022-12-20 07:15 UTC, Mas0nShi commented
Fixes #680

2022-12-20 23:43 UTC, capricorn86 requested changes
Thanks for your contribution @Ben2HellAndBack! :star2:  Just found some very minor things.

2022-12-20 23:43 UTC, capricorn86 commented on packages/happy-dom/src/window/Window.ts
> +		return this?.document?.documentElement?.scrollLeft ?? 0;
```suggestion
		return this.document.documentElement?.scrollLeft ?? 0;
```

2022-12-20 23:43 UTC, capricorn86 commented on packages/happy-dom/src/window/Window.ts
> +		return this?.document?.documentElement?.scrollTop ?? 0;
```suggestion
		return this.document.documentElement?.scrollTop ?? 0;
```

2022-12-28 21:04 UTC, Ben2HellAndBack commented
NP! @capricorn86 all fixed up now 👍

2023-01-04 10:04 UTC, capricorn86 approved these changes

2023-01-04 10:05 UTC, merged