Handle the click on HTMLInputElement checkbox, radio and submit. closes #631
capricorn86/happy-dom pull request #711
Opened 2023-02-02 14:19 UTC by mehdi-valette

This patch includes the implementation of onclick for HTMLInputElement and the unit tests that go with it.

I discovered happy-dom recently, I hope this patch is relevant.

2023-02-02 15:04 UTC, capricorn86 requested changes
Thank you for your contribution! :star2: 

I have found some minor things that we should fix. Otherwise it looks good :+1: 

Please also note that there is an ongoing PR that will improve the "checked" property behaviour:
https://github.com/capricorn86/happy-dom/pull/677/files#diff-bb649479cc3389b9fff9883a1cc18a2b9edc08aac12cb0689ecabf13f21be16bR568

2023-02-02 15:04 UTC, capricorn86 commented on packages/happy-dom/test/nodes/html-input-element/HTMLInputElement.test.ts
> +			expect(submitted).toHaveBeenCalledTimes(1);
```suggestion
			
			let triggeredEvent: Event = null;
			form.addEventListener('submit', (event) => triggeredEvent = event);

			submit.click();
			
			expect(triggeredEvent.target === form).toBe(true);
			expect(triggeredEvent.currentTarget === form).toBe(true);

```

2023-02-02 15:18 UTC, mehdi-valette commented on packages/happy-dom/src/nodes/html-input-element/HTMLInputElement.ts
> +	};
That's much simpler! If I knew that 😅

Just a thought for the line 59  `this.checked = !this.checked`. Do we want it for the radio? If I click on a checked radio it shouldn't uncheck. (Unless it is already handled at another place in the code).

2023-02-02 16:04 UTC, capricorn86 commented on packages/happy-dom/src/nodes/html-input-element/HTMLInputElement.ts
> +	};
I have corrected the code :slightly_smiling_face:

2023-04-15 15:42 UTC, capricorn86 commented
@mehdi-valette I believe that support for this has been added in this PR:
https://github.com/capricorn86/happy-dom/pull/677/files#diff-bb649479cc3389b9fff9883a1cc18a2b9edc08aac12cb0689ecabf13f21be16bR1042

I will close this PR.

2023-04-15 15:42 UTC, closed without merging